---
crio_kubic_versions:
  "1.18": "1.17"
  "1.17": "1.17"
  "1.16": "1.16"

crio_packages:
  - "cri-o-{{ crio_kubic_versions[ kube_version | regex_replace('^v(?P<major>\\d+).(?P<minor>\\d+).(?P<patch>\\d+)$', '\\g<major>.\\g<minor>') ] | default('1.17') }}"

crio_conmon: /usr/bin/conmon
crio_seccomp_profile: ""
crio_runc_path: /usr/lib/cri-o-runc/sbin/runc
