all:
  hosts:
    node1:
      ansible_host: 10.117.32.166
      ansible_ssh_user: vmware
      ip: 10.117.32.166
      access_ip: 10.117.32.166
    node2:
      ansible_host: 10.117.32.163
      ansible_ssh_user: vmware
      ip: 10.117.32.163
      access_ip: 10.117.32.163
    node3:
      ansible_host: 10.117.32.164
      ansible_ssh_user: vmware
      ip: 10.117.32.164
      access_ip: 10.117.32.164
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
